name: first_workflow
on: [push]

jobs:
  writing-a-string:
    runs-on: ubuntu-latest
    steps:
      - name: string output
        run: echo "Hello"
      - name: multiple commands
        run: |
          node -v
          python --version

  parallel-job:
    runs-on: macos-latest
    steps:
      - name: echooes a string
        run: echo "Hello world"
      - name: error step
        run: doesnotexist

  dependant:
    runs-on: windows-latest
    needs: writing-a-string
    steps:
      - name: string output
        run: echo "successful"

  directories-lists:
    runs-on: ubuntu-latest
    steps:
      - name: present directory
        run: |
        pwd
        ls -a
